### PR TITLE
Fix usage description for `ws_max_pending_size` parameter

### LINKED ISSUE #251: ws_max_pending_size option documented as kB instead of bytes
### Tell us about your environment

**AnyCable gem version:** 1.6.0

### What did you do?

Run AnyCable with `ws_max_pending_size` parameter ([documented as `(in kB)`](https://github.com/anycable/anycable/blob/ff7a1e2b4fa00aae325fad8135e1a713e6a21627/cli/options.go#L1161))

```
anycable-go --ws_max_pending_size=50000
```

### What did you expect to happen?

Disconnects when queue exceeds ~50MB, otherwise messages are sent as normal.

### What actually happened?

Disconnects when queue exceeds ~50kB, with message: `{"type":"disconnect","reason":"too_slow","reconnect":true}`

### PR DESCRIPTION
**Pull request by lawrenceshah**
Fixes #251 

- updates usage description to include correct units, and add that 0 means unlimited
- update tests to reflect actual behavior

For reference, the behavior is enforced [here](https://github.com/anycable/anycable/blob/ff7a1e2b4fa00aae325fad8135e1a713e6a21627/node/session.go#L708).

### CODE REVIEW

File: node/session_test.go [hunk 1]
```diff
@@ -1,7 +1,6 @@
 package node
 
 import (
-	"strings"
```
Comment (lawrenceshah) [inline node/session_test.go:4]: drive-by from running `make lint`

**Comment by palkan** [comment]
Thanks!
